# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support

name: Java Ballerina

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install Ballerina
      run: curl https://dist.ballerina.io/downloads/2201.8.1/ballerina-2201.8.1-swan-lake.zip -O
    - name: pwd
      run: pwd
    - name: Unzip
      run: unzip ballerina-2201.8.1-swan-lake.zip
    - name: Path
      run: |
       echo $PATH
       echo $GITHUB_PATH
       echo "/home/runner/work/module-ballerina-auth/module-ballerina-auth/ballerina-2201.8.1-swan-lake/bin" >> $GITHUB_PATH
       echo $PATH
       echo $GITHUB_PATH
    - name: Check Ballerina
      run: bal version 
